Dimension order
macmillancontentscience/torchtransformers pull request #21
Opened 2022-05-20 20:48 UTC by jonthegeek

Standardize dimension order in all functions.

2022-05-20 21:07 UTC, jonthegeek commented
Closes #20.

2022-05-23 17:30 UTC, jonathanbratt requested changes
One very tiny change suggested.

2022-05-23 20:06 UTC, jonathanbratt approved these changes
not merging!

2022-05-24 03:02 UTC, jonathanbratt approved these changes

2022-05-24 03:02 UTC, merged