Link Tokenizer Info to Model
macmillancontentscience/torchtransformers pull request #32
Opened 2022-09-13 22:13 UTC by jonthegeek

Major changes to make models safer.

2022-09-20 20:01 UTC, jonathanbratt requested changes
looking good! Just a few things that we mostly already discussed.

2022-09-20 20:18 UTC, jonthegeek commented on R/luz_callbacks.R
> +    on_fit_begin = function() {
There are other initialization things that run on_fit_begin and I think it's fine for this to run at the default level.

2022-09-20 20:19 UTC, jonthegeek commented on R/luz_callbacks.R
> +        model <- model[[self$submodel_name]]
By default this should be NULL. It's only not NULL if you wrap the pretrained model inside another model, so we can't set a default (other than NULL).

2022-09-21 17:42 UTC, jonathanbratt commented on R/luz_callbacks.R
> +        model <- model[[self$submodel_name]]
Ah, that makes sense. I still think maybe in the future we could make this argument less necessary, but this is fine for now.

2022-09-21 17:43 UTC, jonathanbratt approved these changes

2022-09-21 17:43 UTC, merged